<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class AgendaApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation deleteAgenda
     *
     * Deletes a user by ID.
     *
     * @param string $id Agenda ID (required)
     *
     * @return Http response
     */
    public function deleteAgenda($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteAgenda as a delete method ?');
    }
    /**
     * Operation getAgenda
     *
     * Gets a doc by ID.
     *
     * @param string $id Agenda ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getAgenda($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getAgenda as a get method ?');
    }
    /**
     * Operation updateAgenda
     *
     * Updates a Agenda by ID.
     *
     * @param string $id Agenda ID. (required)
     *
     * @return Http response
     */
    public function updateAgenda($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateAgenda as a put method ?');
    }
    /**
     * Operation allAgendas
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allAgendas()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allAgendas');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allAgendas');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $must_to_do = $input['must_to_do'];


        return response('How about implementing allAgendas as a get method ?');
    }
    /**
     * Operation createAgenda
     *
     * Creates a document.
     *
     *
     * @return Http response
     */
    public function createAgenda()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createAgenda as a post method ?');
    }
}
