<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class ArticleApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation deleteArticle
     *
     * Deletes a user by ID.
     *
     * @param string $id Article ID (required)
     *
     * @return Http response
     */
    public function deleteArticle($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteArticle as a delete method ?');
    }
    /**
     * Operation getArticle
     *
     * Gets a doc by ID.
     *
     * @param string $id Article ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getArticle($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getArticle as a get method ?');
    }
    /**
     * Operation updateArticle
     *
     * Updates a Article by ID.
     *
     * @param string $id Article ID. (required)
     *
     * @return Http response
     */
    public function updateArticle($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateArticle as a put method ?');
    }
    /**
     * Operation allArticles
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allArticles()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allArticles');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allArticles');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $must_to_do = $input['must_to_do'];

        $excerpt = $input['excerpt'];


        return response('How about implementing allArticles as a get method ?');
    }
    /**
     * Operation createArticle
     *
     * Creates a document.
     *
     *
     * @return Http response
     */
    public function createArticle()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createArticle as a post method ?');
    }
}
