<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class BoptionApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation deleteBoption
     *
     * Deletes a user by ID.
     *
     * @param string $id Boption ID (required)
     *
     * @return Http response
     */
    public function deleteBoption($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteBoption as a delete method ?');
    }
    /**
     * Operation getBoption
     *
     * Gets a doc by ID.
     *
     * @param string $id Boption ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getBoption($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getBoption as a get method ?');
    }
    /**
     * Operation updateBoption
     *
     * Updates a Boption by ID.
     *
     * @param string $id Boption ID. (required)
     *
     * @return Http response
     */
    public function updateBoption($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateBoption as a put method ?');
    }
    /**
     * Operation allBoptions
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allBoptions()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allBoptions');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allBoptions');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $must_to_do = $input['must_to_do'];

        $excerpt = $input['excerpt'];


        return response('How about implementing allBoptions as a get method ?');
    }
    /**
     * Operation createBoption
     *
     * Creates a document.
     *
     *
     * @return Http response
     */
    public function createBoption()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createBoption as a post method ?');
    }
}
