<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class BusinessTransfertApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation deleteBusinessTransfert
     *
     * Deletes a user by ID.
     *
     * @param string $id BusinessTransfert ID (required)
     *
     * @return Http response
     */
    public function deleteBusinessTransfert($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteBusinessTransfert as a delete method ?');
    }
    /**
     * Operation getBusinessTransfert
     *
     * Gets a doc by ID.
     *
     * @param string $id BusinessTransfert ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getBusinessTransfert($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getBusinessTransfert as a get method ?');
    }
    /**
     * Operation updateBusinessTransfert
     *
     * Updates a BusinessTransfert by ID.
     *
     * @param string $id BusinessTransfert ID. (required)
     *
     * @return Http response
     */
    public function updateBusinessTransfert($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateBusinessTransfert as a put method ?');
    }
    /**
     * Operation approveBusinessTransfert
     *
     * Approve business.
     *
     * @param string $id BusinessTransfert ID. (required)
     *
     * @return Http response
     */
    public function approveBusinessTransfert($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing approveBusinessTransfert as a put method ?');
    }
    /**
     * Operation rejectBusinessTransfert
     *
     * Reject business.
     *
     * @param string $id BusinessTransfert ID. (required)
     *
     * @return Http response
     */
    public function rejectBusinessTransfert($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing rejectBusinessTransfert as a put method ?');
    }
    /**
     * Operation allBusinessTransfertRequiredDocuments
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allBusinessTransfertRequiredDocuments()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allBusinessTransfertRequiredDocuments');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allBusinessTransfertRequiredDocuments');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $business_id = $input['business_id'];


        return response('How about implementing allBusinessTransfertRequiredDocuments as a get method ?');
    }
    /**
     * Operation allBusinessTransferts
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allBusinessTransferts()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allBusinessTransferts');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allBusinessTransferts');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $excerpt = $input['excerpt'];


        return response('How about implementing allBusinessTransferts as a get method ?');
    }
}
