<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class BusinessRequiredDocumentApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation deleteBusinessRequiredDocument
     *
     * Deletes a user by ID.
     *
     * @param string $id BusinessRequiredDocument ID (required)
     *
     * @return Http response
     */
    public function deleteBusinessRequiredDocument($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteBusinessRequiredDocument as a delete method ?');
    }
    /**
     * Operation getBusinessRequiredDocument
     *
     * Gets a doc by ID.
     *
     * @param string $id BusinessRequiredDocument ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getBusinessRequiredDocument($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getBusinessRequiredDocument as a get method ?');
    }
    /**
     * Operation updateBusinessRequiredDocument
     *
     * Updates a BusinessRequiredDocument by ID.
     *
     * @param string $id BusinessRequiredDocument ID. (required)
     *
     * @return Http response
     */
    public function updateBusinessRequiredDocument($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateBusinessRequiredDocument as a put method ?');
    }
    /**
     * Operation approveBusinessRequiredDocument
     *
     * Approve business.
     *
     * @param string $id BusinessRequiredDocument ID. (required)
     *
     * @return Http response
     */
    public function approveBusinessRequiredDocument($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing approveBusinessRequiredDocument as a put method ?');
    }
    /**
     * Operation rejectBusinessRequiredDocument
     *
     * Reject business.
     *
     * @param string $id BusinessRequiredDocument ID. (required)
     *
     * @return Http response
     */
    public function rejectBusinessRequiredDocument($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing rejectBusinessRequiredDocument as a put method ?');
    }
    /**
     * Operation allBusinessRequiredDocuments
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allBusinessRequiredDocuments()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allBusinessRequiredDocuments');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allBusinessRequiredDocuments');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $business_id = $input['business_id'];


        return response('How about implementing allBusinessRequiredDocuments as a get method ?');
    }
}
