<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class BusinessCategoryApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation allBusinessCategories
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allBusinessCategories()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allBusinessCategories');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allBusinessCategories');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $parent_id = $input['parent_id'];


        return response('How about implementing allBusinessCategories as a get method ?');
    }
    /**
     * Operation createBusinessCategory
     *
     * Creates a document.
     *
     *
     * @return Http response
     */
    public function createBusinessCategory()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createBusinessCategory as a post method ?');
    }
    /**
     * Operation deleteBusinessCategory
     *
     * Deletes a user by ID.
     *
     * @param string $id BusinessCategory ID (required)
     *
     * @return Http response
     */
    public function deleteBusinessCategory($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteBusinessCategory as a delete method ?');
    }
    /**
     * Operation getBusinessCategory
     *
     * Gets a doc by ID.
     *
     * @param string $id BusinessCategory ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getBusinessCategory($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getBusinessCategory as a get method ?');
    }
    /**
     * Operation updateBusinessCategory
     *
     * Updates a BusinessCategory by ID.
     *
     * @param string $id BusinessCategory ID. (required)
     *
     * @return Http response
     */
    public function updateBusinessCategory($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateBusinessCategory as a put method ?');
    }
}
