<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class CalendarApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation deleteCalendar
     *
     * Deletes a user by ID.
     *
     * @param string $id Calendar ID (required)
     *
     * @return Http response
     */
    public function deleteCalendar($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteCalendar as a delete method ?');
    }
    /**
     * Operation getCalendar
     *
     * Gets a doc by ID.
     *
     * @param string $id Calendar ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getCalendar($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getCalendar as a get method ?');
    }
    /**
     * Operation updateCalendar
     *
     * Updates a Calendar by ID.
     *
     * @param string $id Calendar ID. (required)
     *
     * @return Http response
     */
    public function updateCalendar($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateCalendar as a put method ?');
    }
    /**
     * Operation allCalendars
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allCalendars()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allCalendars');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allCalendars');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $must_to_do = $input['must_to_do'];

        $excerpt = $input['excerpt'];


        return response('How about implementing allCalendars as a get method ?');
    }
    /**
     * Operation createCalendar
     *
     * Creates a document.
     *
     *
     * @return Http response
     */
    public function createCalendar()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createCalendar as a post method ?');
    }
}
