<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;
use App\Models\Category;
use App\Models\Document;
use App\Http\Utils\Utils;

class CategoryApiImpl extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation allCategories
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allCategories()
    {
        try {
              $input = Request::all();

                if (!isset($input['limit'])) {
                    throw new \InvalidArgumentException('Missing the required parameter $limit when calling getDocuments');
                }
                $limit = $input['limit'];

                if (!isset($input['page'])) {
                    throw new \InvalidArgumentException('Missing the required parameter $page when calling getDocuments');
                }
                $page = $input['page'];

                //not path params validation

                $limit = isset($input['limit']) ? intval( $input['limit'] ): 10;

                if ($limit == 0) {
                    $limit = 1;
                }

                $page = isset($input['page']) ? intval( $input['page'] ) : 1;

                if( $page == 0 ) {
                    $page = 1;
                }

                $skip = ($page-1) * $limit;

                $query = new Category();
                if( isset($input['searchValue']) && strlen($input['searchValue']) > 0  ) {
                    $orArray = array();
                    $fields = ['label'];
                    // Put search in lowercase
                    $searchValue = strtolower($input['searchValue']);

                    // Extract search fields
                    if( isset($input['searchFields']) ) {
                        $fields = explode(',', $input['searchFields']);
                    }

                    // Iterate on fields to create the query
                    $query = $query->where(function($query) use($fields, $searchValue) {
                        foreach( $fields as $field ) {
                            $query->orWhere($field, 'like', "%" . $searchValue ."%");
                        }
                    });
                }
                // Get total elements in DB
                $total = $query->count();


                $totalPages = ceil( $total / $limit );

                if ($page > $totalPages) {
                    return response()->json([
                    'limit' => $limit,
                    'page' => $page,
                    'pages' => $totalPages,
                    'total' => $total,
                    'rows' => []
                    ]);
                }


                $sortBy = 'created_at';
                $sortOrder = 'asc';

                // Generate sort query
                if( isset($input['sortField']) ) {
                    $data = explode('=', $input['sortField']);
                    if( count($data) == 2 ) {
                        $sortBy = $data[0];
                        $sortOrder = $data[1];
                    }
                }

                $contracts = $query->with('image')->orderBy($sortBy, $sortOrder)->skip($skip)->take($limit)->get();

                return response()->json([
                'limit' => $limit,
                'page' => $page,
                'pages' => $totalPages,
                'total' => $total,
                'rows' => $contracts
                ]);
        } catch (Exception $e) {
            return response()->json([
            'error' => 'Unexpected error',
            'stack' => json_encode(e)
            ], 500);
        }
    }
    /**
     * Operation createCategory
     *
     * Creates a document.
     *
     *
     * @return Http response
     */
    public function createCategory()
    {
        try {
            $decodedToken = Utils::isAuthorized((array)[
            'role' => array('admin'),
            ]);
            if( $decodedToken ) {
                $body = json_decode( Request::instance()->getContent() );

                $category = new Category();
                foreach( $body as $key => $value ) {
                    if ($key !== 'image') {
                        $category->{$key} = $value;
                    }
                }
                if (isset($body->image)) {
                    if ( isset($body->image->id) ) {
                        $image = Document::find($body->image->id);
                    } else {
                        $image = new Document();
                        foreach( $body->image as $key => $value ) {
                            $image->{$key} = $value;
                        }
                        $image->save();
                    }
                    $category->image()->associate($image);
                }
                $category->save();
               
                // $document = Document::create((array)$body);
                return response()->json($category);
            }
            else {
                $unauthorized = Utils::unauthorizedMessage();
                return response()->json($unauthorized->message, $unauthorized->status);
            }
        } catch (Exception $e) {
            return response()->json([
            'error' => 'Unexpected error',
            'stack' => json_encode(e)
            ], 500);
        }
    }
    /**
     * Operation deleteCategory
     *
     * Deletes a user by ID.
     *
     * @param string $id Category ID (required)
     *
     * @return Http response
     */
    public function deleteCategory($id)
    {
        try {
            $decodedToken = Utils::isAuthorized((array)[
            'role' => ['admin']]);

            if( $decodedToken ) {
                $input = Request::all();

                $document = Category::find($id);

                if( !$document ) {
                    $notFound = Utils::notFoundMessage();
                    return response()->json($notFound->message, $notFound->status);
                }

                $document->delete();

                return response()->json([
                'success' => true
                ]);
            }
            else {
                $unauthorized = Utils::unauthorizedMessage();
                return response()->json($unauthorized->message, $unauthorized->status);
            }
        } catch (Exception $e) {
            return response()->json([
            'error' => 'Unexpected error',
            'stack' => json_encode(e)
            ], 500);
        }
    }
    /**
     * Operation getCategory
     *
     * Gets a doc by ID.
     *
     * @param string $id Category ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getCategory($id)
    {
        try {
            $query = Category::find($id)->with('image');
            $document = $query->first();

            if( !$document ) {
                $notFound = Utils::notFoundMessage();
                return response()->json($notFound->message, $notFound->status);
            }

            return response()->json($document);
        } catch (Exception $e) {
            return response()->json([
            'error' => 'Unexpected error',
            'stack' => json_encode(e)
            ], 500);
        }
    }
    /**
     * Operation updateCategory
     *
     * Updates a Category by ID.
     *
     * @param string $id Category ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function updateCategory($id)
    {
        try {
            $decodedToken = Utils::isAuthorized((array)[
            'role' => ['admin']]);

            if( $decodedToken ) {
                $input = Request::all();
                $body = json_decode( Request::instance()->getContent() );

                // Search in DB
                $document = Category::find($id);

                if( !$document ) { // Stop request if the user has not been found
                    $notFound = Utils::notFoundMessage();
                    return response()->json($notFound->message, $notFound->status);
                }
                unset($body->created_at);
                unset($body->updated_at);

                foreach( $body as $key => $value ) {
                    if($key !== 'image') {
                        $document->{$key} = $value;
                    }
                }
                if (isset($body->image)) {
                    if ( isset($body->image->id) ) {
                        $image = Document::find($body->image->id);
                    } else {
                        $image = new Document();
                        foreach( $body->image as $key => $value ) {
                            $image->{$key} = $value;
                        }
                        $image->save();
                    }
                    $document->image()->associate($image);
                }
                $document->save();
                return response()->json($document);
            }
            else {
                $unauthorized = Utils::unauthorizedMessage();
                return response()->json($unauthorized->message, $unauthorized->status);
            }
        } catch (Exception $e) {
            return response()->json([
            'error' => 'Unexpected error',
            'stack' => json_encode(e)
            ], 500);
        }
    }
}
