<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class FileApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation downloadFile
     *
     * download a file.
     *
     *
     * @return Http response
     */
    public function downloadFile()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['path'])) {
            throw new \InvalidArgumentException('Missing the required parameter $path when calling downloadFile');
        }
        $path = $input['path'];

        if (!isset($input['final_name'])) {
            throw new \InvalidArgumentException('Missing the required parameter $final_name when calling downloadFile');
        }
        $final_name = $input['final_name'];


        return response('How about implementing downloadFile as a get method ?');
    }
    /**
     * Operation getFile
     *
     * Get a file.
     *
     *
     * @return Http response
     */
    public function getFile()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['path'])) {
            throw new \InvalidArgumentException('Missing the required parameter $path when calling getFile');
        }
        $path = $input['path'];


        return response('How about implementing getFile as a get method ?');
    }
    /**
     * Operation previewFile
     *
     * preview a file.
     *
     *
     * @return Http response
     */
    public function previewFile()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['path'])) {
            throw new \InvalidArgumentException('Missing the required parameter $path when calling previewFile');
        }
        $path = $input['path'];


        return response('How about implementing previewFile as a get method ?');
    }
}
