<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;
use App\Models\News;
use App\Models\Document;
use App\Http\Utils\Utils;
use App\Models\Category;

class NewsApiImpl extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation allNewss
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allNews()
    {
        try {
              $input = Request::all();

                if (!isset($input['limit'])) {
                    throw new \InvalidArgumentException('Missing the required parameter $limit when calling getDocuments');
                }
                $limit = $input['limit'];

                if (!isset($input['page'])) {
                    throw new \InvalidArgumentException('Missing the required parameter $page when calling getDocuments');
                }
                $page = $input['page'];

                //not path params validation

                $limit = isset($input['limit']) ? intval( $input['limit'] ): 10;

                if ($limit == 0) {
                    $limit = 1;
                }

                $page = isset($input['page']) ? intval( $input['page'] ) : 1;

                if( $page == 0 ) {
                    $page = 1;
                }

                $skip = ($page-1) * $limit;

                $query = new News();
                if( isset($input['searchValue']) && strlen($input['searchValue']) > 0  ) {
                    $orArray = array();
                    $fields = ['title'];
                    // Put search in lowercase
                    $searchValue = strtolower($input['searchValue']);

                    // Extract search fields
                    if( isset($input['searchFields']) ) {
                        $fields = explode(',', $input['searchFields']);
                    }

                    // Iterate on fields to create the query
                    $query = $query->where(function($query) use($fields, $searchValue) {
                        foreach( $fields as $field ) {
                            $query->orWhere($field, 'like', "%" . $searchValue ."%");
                        }
                    });
                }
                // Get total elements in DB
                $total = $query->count();


                $totalPages = ceil( $total / $limit );

                if ($page > $totalPages) {
                    return response()->json([
                    'limit' => $limit,
                    'page' => $page,
                    'pages' => $totalPages,
                    'total' => $total,
                    'rows' => []
                    ]);
                }


                $sortBy = 'created_at';
                $sortOrder = 'asc';

                // Generate sort query
                if( isset($input['sortField']) ) {
                    $data = explode('=', $input['sortField']);
                    if( count($data) == 2 ) {
                        $sortBy = $data[0];
                        $sortOrder = $data[1];
                    }
                }

                $documents = $query->with('thumbnail', 'banner')->orderBy($sortBy, $sortOrder)->skip($skip)->take($limit)->get();
                if (isset($input['excerpt'])) {
                    foreach($documents as $doc) {
                        $doc->content = $doc->excerpt(150);
                    }
                }
                return response()->json([
                'limit' => $limit,
                'page' => $page,
                'pages' => $totalPages,
                'total' => $total,
                'rows' => $documents
                ]);
        } catch (Exception $e) {
            return response()->json([
            'error' => 'Unexpected error',
            'stack' => json_encode(e)
            ], 500);
        }
    }
    /**
     * Operation createNews
     *
     * Creates a document.
     *
     *
     * @return Http response
     */
    public function createNews()
    {

        try {
            $decodedToken = Utils::isAuthorized((array)[
            'role' => array('admin'),
            ]);
            if( $decodedToken ) {
                $body = json_decode( Request::instance()->getContent() );

                $news = new News();
                foreach( $body as $key => $value ) {
                    if ($key !== 'thumbnail' && $key !== 'images' && $key !== 'banner') {
                        $news->{$key} = $value;
                    }
                }
                $news->posted_at = \Carbon\Carbon::now()->format('Y-m-d H:i:s');
                $news->author_id = $decodedToken->userId;
                if (isset($body->images)) {
                    $imagesToAttach = array();
                    foreach($body->images as $docImage) {
                        if ( isset($docImage->id) ) {
                            $image = Document::find($docImage->id);
                        } else {
                            $image = new Document();
                            foreach( $docImage as $key => $value ) {
                                $image->{$key} = $value;
                            }
                            $image->save();

                        }
                        array_push($imagesToAttach, $image->id);
                    }
                }
                if (isset($body->categories)) {
                    $categoriesToAttach = array();
                    foreach($body->categories as $docCat) {
                        if ( isset($docCat->id) ) {
                            $cat = Category::find($docCat->id);
                        } else {
                            $cat = new Category();
                            foreach( $docCat as $key => $value ) {
                                $cat->{$key} = $value;
                            }
                            $cat->save();
                        }
                        array_push($categoriesToAttach, $cat->id);
                    }
                }
                if (isset($body->thumbnail)) {
                    if ( isset($body->thumbnail->id) ) {
                        $thumbnail = Document::find($body->thumbnail->id);
                    } else {
                        $thumbnail = new Document();
                        foreach( $body->thumbnail as $key => $value ) {
                            $thumbnail->{$key} = $value;
                        }
                        $thumbnail->save();
                    }
                    $news->thumbnail()->associate($thumbnail);
                }
                if (isset($body->banner)) {
                    if ( isset($body->banner->id) ) {
                        $banner = Document::find($body->banner->id);
                    } else {
                        $banner = new Document();
                        foreach( $body->banner as $key => $value ) {
                            $banner->{$key} = $value;
                        }
                        $banner->save();
                    }
                    $news->banner()->associate($banner);
                }
                $news->save();
                if (isset($categoriesToAttach) && count($categoriesToAttach) > 0) {
                    $news->categories()->attach($categoriesToAttach);
                }
                if (isset($imagesToAttach) && count($imagesToAttach) > 0) {
                    $news->images()->attach($imagesToAttach);
                }
              
                
               
                // $document = Document::create((array)$body);
                return response()->json($news);
            }
            else {
                $unauthorized = Utils::unauthorizedMessage();
                return response()->json($unauthorized->message, $unauthorized->status);
            }
        } catch (Exception $e) {
            return response()->json([
            'error' => 'Unexpected error',
            'stack' => json_encode(e)
            ], 500);
        }

/*
        try {
            $decodedToken = Utils::isAuthorized((array)[
            'role' => array('admin'),
            ]);
            if( $decodedToken ) {
                $body = json_decode( Request::instance()->getContent() );

                $news = new News();
                foreach( $body as $key => $value ) {
                    if ($key !== 'thumbnail' && $key !== 'banner') {
                        $news->{$key} = $value;
                    }
                }
                $news->posted_at = \Carbon\Carbon::now()->format('Y-m-d H:i:s');
                $news->author_id = $decodedToken->userId;
                if (isset($body->thumbnail)) {
                    if ( isset($body->thumbnail->id) ) {
                        $thumbnail = Document::find($body->thumbnail->id);
                    } else {
                        $thumbnail = new Document();
                        foreach( $body->thumbnail as $key => $value ) {
                            $thumbnail->{$key} = $value;
                        }
                        $thumbnail->save();
                    }
                    $news->thumbnail()->associate($thumbnail);
                }
                if (isset($body->banner)) {
                    if ( isset($body->banner->id) ) {
                        $banner = Document::find($body->banner->id);
                    } else {
                        $banner = new Document();
                        foreach( $body->banner as $key => $value ) {
                            $banner->{$key} = $value;
                        }
                        $banner->save();
                    }
                    $news->banner()->associate($banner);
                }
                $news->save();
              
                
               
                // $document = Document::create((array)$body);
                return response()->json($news);
            }
            else {
                $unauthorized = Utils::unauthorizedMessage();
                return response()->json($unauthorized->message, $unauthorized->status);
            }
        } catch (Exception $e) {
            return response()->json([
            'error' => 'Unexpected error',
            'stack' => json_encode(e)
            ], 500);
        }
        */
    }
    /**
     * Operation deleteNews
     *
     * Deletes a user by ID.
     *
     * @param string $id News ID (required)
     *
     * @return Http response
     */
    public function deleteNews($id)
    {
        try {
            $decodedToken = Utils::isAuthorized((array)[
            'role' => ['admin']]);

            if( $decodedToken ) {
                $input = Request::all();

                $document = News::find($id);

                if( !$document ) {
                    $notFound = Utils::notFoundMessage();
                    return response()->json($notFound->message, $notFound->status);
                }

                $document->delete();

                return response()->json([
                'success' => true
                ]);
            }
            else {
                $unauthorized = Utils::unauthorizedMessage();
                return response()->json($unauthorized->message, $unauthorized->status);
            }
        } catch (Exception $e) {
            return response()->json([
            'error' => 'Unexpected error',
            'stack' => json_encode(e)
            ], 500);
        }
    }
    /**
     * Operation getNews
     *
     * Gets a doc by ID.
     *
     * @param string $id News ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getNews($id)
    {
        try {
            $query = News::where('id', $id)->with('thumbnail', 'banner', 'images');
            $document = $query->first();

            if( !$document ) {
                $notFound = Utils::notFoundMessage();
                return response()->json($notFound->message, $notFound->status);
            }

            return response()->json($document);
        } catch (Exception $e) {
            return response()->json([
            'error' => 'Unexpected error',
            'stack' => json_encode(e)
            ], 500);
        }
    }
    /**
     * Operation updateNews
     *
     * Updates a News by ID.
     *
     * @param string $id News ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function updateNews($id)
    {
        try {
            $decodedToken = Utils::isAuthorized((array)[
            'role' => ['admin']]);

            if( $decodedToken ) {
                $input = Request::all();
                $body = json_decode( Request::instance()->getContent() );

                // Search in DB
                $document = News::find($id);

                if( !$document ) { // Stop request if the user has not been found
                    $notFound = Utils::notFoundMessage();
                    return response()->json($notFound->message, $notFound->status);
                }
                unset($body->created_at);
                unset($body->updated_at);

                foreach( $body as $key => $value ) {
                    if ($key !== 'thumbnail' && $key !== 'images' && $key !== 'banner') {
                        $document->{$key} = $value;
                    }
                }
                if (isset($body->thumbnail)) {
                    if ( isset($body->thumbnail->id) ) {
                        $thumbnail = Document::find($body->thumbnail->id);
                    } else {
                        $thumbnail = new Document();
                        foreach( $body->thumbnail as $key => $value ) {
                            $thumbnail->{$key} = $value;
                        }
                        $thumbnail->save();
                    }
                    $document->thumbnail()->associate($thumbnail);
                }
                if (isset($body->banner)) {
                    if ( isset($body->banner->id) ) {
                        $banner = Document::find($body->banner->id);
                    } else {
                        $banner = new Document();
                        foreach( $body->banner as $key => $value ) {
                            $banner->{$key} = $value;
                        }
                        $banner->save();
                    }
                    $document->banner()->associate($banner);
                }
                if (isset($body->images)) {
                    $imagesToAttach = array();
                    foreach($body->images as $docImage) {
                        if ( isset($docImage->id) ) {
                            $image = Document::find($docImage->id);
                        } else {
                            $image = new Document();
                            foreach( $docImage as $key => $value ) {
                                $image->{$key} = $value;
                            }
                            $image->save();

                        }
                        array_push($imagesToAttach, $image->id);
                    }
                }
                if (isset($body->categories)) {

                    $categoriesToAttach = array();
                    foreach($body->categories as $docCat) {
                        if ( isset($docCat->id) ) {
                            $cat = Category::find($docCat->id);
                        } else {
                            $cat = new Category();
                            foreach( $docCat as $key => $value ) {
                                $cat->{$key} = $value;
                            }
                            $cat->save();
                        }
                        array_push($categoriesToAttach, $cat->id);
                    }
                }
                // detach
                $document->save();
                // new attach
                if (isset($categoriesToAttach) && count($categoriesToAttach) > 0) {
                    $document->categories()->sync($categoriesToAttach);
                }
                if (isset($imagesToAttach) && count($imagesToAttach) > 0) {
                    $document->images()->sync($imagesToAttach);
                }
                return response()->json($document);
            }
            else {
                $unauthorized = Utils::unauthorizedMessage();
                return response()->json($unauthorized->message, $unauthorized->status);
            }
        } catch (Exception $e) {
            return response()->json([
            'error' => 'Unexpected error',
            'stack' => json_encode(e)
            ], 500);
        }
    }
}
