<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class NewsApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation allNews
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allNews()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allNews');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allNews');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $excerpt = $input['excerpt'];


        return response('How about implementing allNews as a get method ?');
    }
    /**
     * Operation createNews
     *
     * Creates a document.
     *
     *
     * @return Http response
     */
    public function createNews()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createNews as a post method ?');
    }
    /**
     * Operation deleteNews
     *
     * Deletes a user by ID.
     *
     * @param string $id News ID (required)
     *
     * @return Http response
     */
    public function deleteNews($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteNews as a delete method ?');
    }
    /**
     * Operation getNews
     *
     * Gets a doc by ID.
     *
     * @param string $id News ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getNews($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getNews as a get method ?');
    }
    /**
     * Operation updateNews
     *
     * Updates a News by ID.
     *
     * @param string $id News ID. (required)
     *
     * @return Http response
     */
    public function updateNews($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateNews as a put method ?');
    }
}
