<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class RequiredDocumentApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation deleteRequiredDocument
     *
     * Deletes a user by ID.
     *
     * @param string $id RequiredDocument ID (required)
     *
     * @return Http response
     */
    public function deleteRequiredDocument($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteRequiredDocument as a delete method ?');
    }
    /**
     * Operation getRequiredDocument
     *
     * Gets a doc by ID.
     *
     * @param string $id RequiredDocument ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getRequiredDocument($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getRequiredDocument as a get method ?');
    }
    /**
     * Operation updateRequiredDocument
     *
     * Updates a RequiredDocument by ID.
     *
     * @param string $id RequiredDocument ID. (required)
     *
     * @return Http response
     */
    public function updateRequiredDocument($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateRequiredDocument as a put method ?');
    }
    /**
     * Operation allRequiredDocuments
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allRequiredDocuments()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allRequiredDocuments');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allRequiredDocuments');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $excerpt = $input['excerpt'];


        return response('How about implementing allRequiredDocuments as a get method ?');
    }
    /**
     * Operation createRequiredDocument
     *
     * Creates a document.
     *
     *
     * @return Http response
     */
    public function createRequiredDocument()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createRequiredDocument as a post method ?');
    }
}
