<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class RoadtoladakhApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation allRoadtoladakh
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allRoadtoladakh()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allRoadtoladakh');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allRoadtoladakh');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $excerpt = $input['excerpt'];


        return response('How about implementing allRoadtoladakh as a get method ?');
    }
    /**
     * Operation createRoadtoladakh
     *
     * Creates a document.
     *
     *
     * @return Http response
     */
    public function createRoadtoladakh()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createRoadtoladakh as a post method ?');
    }
    /**
     * Operation deleteRoadtoladakh
     *
     * Deletes a user by ID.
     *
     * @param string $id Roadtoladakh ID (required)
     *
     * @return Http response
     */
    public function deleteRoadtoladakh($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteRoadtoladakh as a delete method ?');
    }
    /**
     * Operation getRoadtoladakh
     *
     * Gets a doc by ID.
     *
     * @param string $id Roadtoladakh ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getRoadtoladakh($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getRoadtoladakh as a get method ?');
    }
    /**
     * Operation updateRoadtoladakh
     *
     * Updates a Roadtoladakh by ID.
     *
     * @param string $id Roadtoladakh ID. (required)
     *
     * @return Http response
     */
    public function updateRoadtoladakh($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateRoadtoladakh as a put method ?');
    }
}
