<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class SliderApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation deleteSlider
     *
     * Deletes a user by ID.
     *
     * @param string $id Slider ID (required)
     *
     * @return Http response
     */
    public function deleteSlider($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteSlider as a delete method ?');
    }
    /**
     * Operation getSlider
     *
     * Gets a doc by ID.
     *
     * @param string $id Slider ID. (required)
     *
     * @return Http response
     */
    public function getSlider($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getSlider as a get method ?');
    }
    /**
     * Operation updateSlider
     *
     * Updates a Slider by ID.
     *
     * @param string $id Slider ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function updateSlider($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateSlider as a put method ?');
    }
    /**
     * Operation allSliders
     *
     * Returns a list of documents..
     *
     *
     * @return Http response
     */
    public function allSliders()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling allSliders');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling allSliders');
        }
        $page = $input['page'];

        $sort_field = $input['sort_field'];

        $search_value = $input['search_value'];

        $search_fields = $input['search_fields'];

        $excerpt = $input['excerpt'];


        return response('How about implementing allSliders as a get method ?');
    }
    /**
     * Operation createSlider
     *
     * Creates a document.
     *
     *
     * @return Http response
     */
    public function createSlider()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createSlider as a post method ?');
    }
}
