<?php

/**
 * Ladakh swagger
 * Documentation for the ladakh platform
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers\Api\V1;

use Illuminate\Support\Facades\Request;

class UsersApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation createUser
     *
     * Creates a user.
     *
     *
     * @return Http response
     */
    public function createUser()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing createUser as a post method ?');
    }
    /**
     * Operation getUsers
     *
     * Returns a list of users..
     *
     *
     * @return Http response
     */
    public function getUsers()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['limit'])) {
            throw new \InvalidArgumentException('Missing the required parameter $limit when calling getUsers');
        }
        $limit = $input['limit'];

        if (!isset($input['page'])) {
            throw new \InvalidArgumentException('Missing the required parameter $page when calling getUsers');
        }
        $page = $input['page'];

        $role = $input['role'];

        $search_value = $input['search_value'];

        $employee_id = $input['employee_id'];

        $search_fields = $input['search_fields'];

        $sort_field = $input['sort_field'];

        $unaffected = $input['unaffected'];

        $archived = $input['archived'];

        $last_updated = $input['last_updated'];

        $deleted = $input['deleted'];


        return response('How about implementing getUsers as a get method ?');
    }
    /**
     * Operation deleteUser
     *
     * Deletes a user by ID.
     *
     * @param string $id User ID (required)
     *
     * @return Http response
     */
    public function deleteUser($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteUser as a delete method ?');
    }
    /**
     * Operation getUser
     *
     * Gets a user by ID.
     *
     * @param string $id User ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function getUser($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getUser as a get method ?');
    }
    /**
     * Operation updateUser
     *
     * Updates a User by ID.
     *
     * @param string $id User ID. If called from the application, can be \&quot;me\&quot;. (required)
     *
     * @return Http response
     */
    public function updateUser($id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateUser as a put method ?');
    }
}
